version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "${PORT}:${PORT}"

  db:
    ports:
      - "${DB_EXPOSED_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - budcalc_db_dev_data:/var/lib/postgresql/data

  cache:
    volumes:
      - budcalc_redis_dev_data:/data

volumes:
  budcalc_db_dev_data:
    external: true
  budcalc_redis_dev_data:
    external: true
